### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by ayb** [QuantConnect/quantconnect-cli#10]
This worked for me a few days ago but I am constantly getting an error now when attempting to do anything that interacts with your API.

`SyntaxError: Unexpected token {`

i.e. `qcli projects:info`, `qcli files:pull`, `qcli projects:list`, `qcli init`, etc.

Is it possible there is a recently introduced JSON error with one of the API endpoints that is causing this? 

Is there a way to trace the parsing to try to identify if there is a file error on my end?  

Any help would be appreciated.

**Comment by jmerle** [comment]
That's odd. I cannot reproduce it and by the error it seems like one of the CLI's internal source files has a syntax error. Could you try reinstalling the CLI to make sure you have the "original" version? You can uninstall by running `npm uninstall -g quantconnect-cli` or `yarn global remove quantconnect-cli` (depending on which package manager you use) and reinstall using the command in the readme.

**Comment by ayb** [comment]
@jmerle I think I have isolated the issue to my use of nvm.  I hadn't thought of setting the node version for my folders.

When I'm running 12.x it seems to work fine.  But if set to an older version (such as 8.9.x) I get that syntax error.

With that in mind I think I can close this out.  Thank you and happy new year :)
