### ISSUE TITLE
Possible to start live trading from cli?

### ISSUE THREAD

**Issue by cnaccio** [QuantConnect/quantconnect-cli#3]
Any possibility of adding a command to start live trading for a project?

**Comment by jmerle** [comment]
Unfortunately not. While there is an API endpoint to start live trading for an algorithm, there is no way to programmatically retrieve details like which brokerages are available in the cloud, which credentials each brokerage needs, what the important notes for each brokerage are and so on (basically all text in the "Go Live" wizard in the IDE).

**Comment by jaredbroad** [comment]
>there is no way to programmatically retrieve details like which brokerages are available in the cloud, which credentials each brokerage needs, what the important notes for each brokerage are and so on (basically all text in the "Go Live" wizard in the IDE).

While no way to _programatically_ fetch those -- they change every 12 months, so seems fair to hard code the config each needs? We hard code them in LEAN LiveAlgorithmSettings
https://github.com/QuantConnect/Lean/blob/d2eae2f652f741b77267c0517941aa27564899d7/Common/Api/LiveAlgorithmSettings.cs#L214 

I'd suggest yes -- there is 100% a way but not implemented yet =)

**Comment by jmerle** [comment]
Hmm sure, if those details don't change often I agree it's not that bad of an idea to hardcode them. I'll implement a hardcoded version later this week.

**Comment by cnaccio** [comment]
You guys are awesome! I love how reasonable/flexible you guys are when it comes to making the solution better. I think this is a really powerful addition, with a great investment/reward payoff. Thanks guys!

**Comment by jmerle** [comment]
Implemented in https://github.com/QuantConnect/quantconnect-cli/commit/52479336727dceb6c9d38e0f54278d26154d3905, will go live later this week:
![Screenshot from 2020-11-27 20-04-12](https://user-images.githubusercontent.com/14951909/100478667-2e2c4380-30ec-11eb-9168-b2cd5f8c2ddc.png)

**Comment by jmerle** [comment]
Released in [1.4.0](https://github.com/QuantConnect/quantconnect-cli/releases/tag/v1.4.0) along with some other commands to better manage live trading from the CLI and some unrelated bug fixes.

**Comment by cnaccio** [comment]
This is sick. Thanks for getting this out so quickly. We'll test it out for ya!
